# get statisticslanguages
GET http://localhost:8001/general/version

# get author 
GET http://localhost:8001/philippines/persons/1517

# get author: debería dar un error; how to handle this?
GET http://localhost:8001/philippines/persons/xxx



