# get statisticslanguages
GET http://localhost:8001/philippines/statistics/general/

# get statisticslanguages
GET http://localhost:8001/philippines/statistics/keys/

# get statisticslanguages
GET http://localhost:8001/general/version

# get author 
GET http://localhost:8001/philippines/persons/

# get author 
GET http://localhost:8001/philippines/persons/mostinfo/

# get author 
GET http://localhost:8001/philippines/persons/720

# get author: debería dar un error; how to handle this?
GET http://localhost:8001/philippines/persons/xxx

# get positions
GET http://localhost:8001/philippines/positions/

# get positions deetails
GET http://localhost:8001/philippines/positions/vicario

# get missions
GET http://localhost:8001/philippines/missions/general/

# get missions
GET http://localhost:8001/philippines/others/languages/

# get births, deaths...
GET http://localhost:8001/philippines/persons/birthsdeaths/

# professions
GET http://localhost:8001/philippines/professions/

# resignations
GET http://localhost:8001/philippines/persons/resignations/

# otro
GET http://localhost:8001/health





